### ISSUE TITLE
[Suggestion] Change wording for the gamelog event notifications (I've offered a few suggestions)

### ISSUE THREAD

**Issue by puddles54** [kirnosenko/BannerlordMods#1]
I have a small suggestion for the gamelog event notifcation text. The way it's worded currently sounds a bit weird or ungrammatical, (e.g. ""{kingdom} was destroyed so clan {clan.Name} abandon it to find a new one."). I'm no programmer but I took a look through your code in the file `SeparateBehaviors.cs` I have a couple suggestions to improve it.

Line 71:
`GameLog.Warn($"Clan {clan.Name} is leaving {kingdom} to found their own {rebelKingdom}.");`

I suggest one of the following instead:
> **The ClanName have broken from OldKingdomName to found the NewKingdomName**
> **The ClanName have declared their independence from OldKingdomName and have established the NewKingdomName**

So if the Khergit separate for example it would be like so:
> **The Khergit have broken from Khuzait to found the Khergit Khanate.**
> **The Khergit have declared their independence from Khuzait and have established the Khergit Khanate.**

Line 83:
'GameLog.Warn($"{kingdom} was destroyed so clan {clan.Name} abandon it to find a new one.");'
 
I suggest the following:
> **The NewKingdomName has been destroyed and the ClanName are in search of a new sovereign.**
> **The NewKingdomName has been destroyed. The ClanName have abandoned it in search of a new sovereign.**

And the Khergit example again:
> **The Khergit Khanate has been destroyed and the Khergit are in search of a new sovereign.**
> **The Khergit Khanate has been destroyed. The Khergit have abandoned it in search of a new sovereign.**

I think searching for a "new sovereign" fits better than a "new kingdom" as in the time period which inspired the game's setting loyalty and service was really directed more at an actual individual person rather than a nation-state. In other words people served the King rather than the Kingdom.

Anyway, just my suggestion. Those are the only two lines of text for the game log I found, so I'm not sure if there's more.

**Comment by kirnosenko** [comment]
It makes sense. I will fix it in next update.
