### ISSUE TITLE
[Suggestion] Change Empire sepratist's faction name from "ClanName's Empire" to "Empire of ClanName"

### ISSUE THREAD

**Issue by puddles54** [kirnosenko/BannerlordMods#2]
I'm back with one more suggestion for the text, mostly because it's something I overlooked last time. My bad. With the new wording for when an Empire clan breaks from their kingdom it'll say something like "Mestricaros has broken from the Western Empire and has founded **the** Mestricaros**'s** Empire". And similar when one is destroyed it says something like "**The** Varros**'s** Empire has been destroyed and the Varros are in search of a new sovereign."

You could probably add a conditional statement of some kind in there to not use 'the' for Empire clans, but I'd suggest changing the names of new Empire factions to "Empire of ClanName" (with no 'the' before the clan name, as I just think it sounds better with Empire clan names). The reasons for this are follows:

1. Easily solves the ungrammatical "the" in both new/destroyed Empire kingdoms
2. Solves the -s's for clan names that end with an 'S' (not a big issue, but technically when the Clan name ends with an 'S' the possessive should end with just the apostrophe and not the possessive 's' (e.g. Varros' Empire)
3. New Empire kingdoms are all nice and organized together (alphabetically) in the encyclopedia.

Anyway, my bad for not noticing the issue with my last suggestion. Thanks for making this mod, I'm loving it on my campaigns and I'd have a hard time playing without it now!

**Comment by kirnosenko** [comment]
Will fix.
